// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUH_pqv4DwcandRjqU8fVtXzj2Sf4AgQ0',
    appId: '1:756376073909:web:a086d9e8887bec4d5b70fc',
    messagingSenderId: '756376073909',
    projectId: 'freelago',
    authDomain: 'freelago.firebaseapp.com',
    storageBucket: 'freelago.firebasestorage.app',
    measurementId: 'G-1WKEKWJGYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OL65LIB7gtAhIqWKhGmeqXoA0z0CxNM',
    appId: '1:756376073909:android:038ca7a22ee83a445b70fc',
    messagingSenderId: '756376073909',
    projectId: 'freelago',
    storageBucket: 'freelago.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-azWOS8NshblVzp0nmbryvr3yNm6Wqxw',
    appId: '1:756376073909:ios:569d95d155c1399b5b70fc',
    messagingSenderId: '756376073909',
    projectId: 'freelago',
    storageBucket: 'freelago.firebasestorage.app',
    iosBundleId: 'com.example.freelago',
  );
}
